/********************************************************************
* lib/StPhiMakerDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error lib/StPhiMakerDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableStPhiMakerDict();
extern void G__cpp_setup_inheritanceStPhiMakerDict();
extern void G__cpp_setup_typetableStPhiMakerDict();
extern void G__cpp_setup_memvarStPhiMakerDict();
extern void G__cpp_setup_globalStPhiMakerDict();
extern void G__cpp_setup_memfuncStPhiMakerDict();
extern void G__cpp_setup_funcStPhiMakerDict();
extern void G__set_cpp_environmentStPhiMakerDict();
}


#include "/tmp/rootcint_V4yw9S.h"
